### ISSUE TITLE
Interference with js2-mode

### ISSUE THREAD

**Issue by ryanprior** [DarthFennec/highlight-indent-guides#1]
highlight-indent-guides works great with every language mode I've tried except `js2-mode`, which has some sort of conflict.

When a source file is first loaded, the guides are shown but `js2-mode`'s syntax highlighting is not active. Upon making changes in the buffer, portions of the syntax will be highlighted but the guides disappear.

`highlight-indentation-mode` works fine with `js2-mode`, if that's any help. But I like the way this mode looks much better.

**Comment by DarthFennec** [comment]
I think my latest commit should fix this, and any similar problems in other modes. Please let me know if it does any good.

**Comment by ryanprior** [comment]
I've been testing this the last few days and it's been consistently good. Thank you for the fix, I'm glad to be using this mode again!

**Comment by DarthFennec** [comment]
Cool, good to hear!
