### ISSUE TITLE
Leave cursor type unchanged over bitmap guides

### ISSUE THREAD

**Issue by agreselin** [DarthFennec/highlight-indent-guides#105]
I use a bar cursor, via `(setq-default cursor-type 'bar)`. With `highlight-indent-guides-method` set to `'bitmap` it becomes an empty box when it's over an indentation guide. Is there a way to avoid that?

![Screenshot from 2020-11-29 20-11-15](https://user-images.githubusercontent.com/22297948/100551126-1fc26100-327f-11eb-8bca-63cea23459b6.png)

**Comment by DarthFennec** [comment]
Yeah, I've had the same issue and I haven't found a way to avoid it. Emacs seems to force the cursor to box when it's on any bitmap image for whatever reason. I've just gotten used to it, but it is rather obnoxious.

**Comment by agreselin** [comment]
Thanks anyway. Lawlist on [emacs.se](https://emacs.stackexchange.com/questions/9882/selecting-the-cursor-type-when-using-an-overlay-cursor-property) had the same problem and he too didn't find a proper solution. Gotta love your 90s graphics when you use emacs :-)

**Comment by DarthFennec** [comment]
Yeah, for all of emacs' flexibility, there are just some things it likes to be stubborn about.
