### ISSUE TITLE
can't load seq in GNU Emacs 24.3.1 (i386-mingw-nt6.2.9200)

### ISSUE THREAD

**Issue by silaoA** [DarthFennec/highlight-indent-guides#11]
I'am really loving this highlight-indent-guides and planning to replace it with the weird highlight-indentation. I put highlight-indent-guides.el into my site-lisp directory, copy following lines in dot emacs file and restart emacs [GNU Emacs 24.3.1 (i386-mingw-nt6.2.9200)] as usual ：
(require 'highlight-indent-guides)
(setq highlight-indent-guides-method 'character)
(add-hook 'prog-mode-hook 'highlight-indent-guides-mode)
but emacs complains "cant't load file seq", I also found (require 'seq) in highlight-indent-guides.el at line 73.
Is there any possible alternative to fix this？   
many thanks!

**Comment by DarthFennec** [comment]
Weird, I thought seq was standard everywhere but I guess not. I've just updated the code to not use that file, so it should work for you now.

**Comment by silaoA** [comment]
I' sorry having to report that Emacs complains again when I evaluate my dot emacs buffer.
eval-buffer: Symbol's function definition is void: advice-add

**Comment by DarthFennec** [comment]
The `advice-add` function was introduced in emacs 24.4, so it looks like your version is too old. I've updated the plugin to use the older advice style `defadvice`, so it should work in your version now.

**Comment by silaoA** [comment]
yes it works, thank you !

**Comment by DarthFennec** [comment]
Cool, I'm glad ^^
