### ISSUE TITLE
highlight-indent-guides breaks load-theme with ivy

### ISSUE THREAD

**Issue by thblt** [DarthFennec/highlight-indent-guides#12]
From emacs -Q

Evaluate this:

~~~
(require 'package)
(package-initialize)

(require 'counsel)
(require 'highlight-indent-guides)

(ivy-mode)
~~~

Then:

`M-x load-theme` results in the following error:

~~~
apply: Wrong number of arguments: #[(theme &optional no-confirm no-enable) "Æ!

**Comment by thblt** [comment]
(Continued.  The original message seems to have been truncated due to weird characters in the error message.)

 - Commenting out `(require 'highlight-indent-guides)` fixes the problem.
 - `counsel-load-theme` is not affected, only `load-theme` with `ivy-mode`.

Here's a screenshot of the error:

![2017-01-05-150106_1440x900_scrot](https://cloud.githubusercontent.com/assets/2453136/21683027/cb3d8ca2-d357-11e6-9d48-e12f22048cc1.png)

**Comment by thblt** [comment]
One last thing, sorry for the flood:  I can reproduce the bug in Emacs 24.5 and Emacs 25.1 from official repos in Debian Stable.  Emacs 25 grabs packages from melpa stable if possible, 24 gets everything from Melpa.

**Comment by DarthFennec** [comment]
I think this is an issue with the way `advice-add` works with commands, conflicting with `ivy`s custom `completing-read`. I've updated it to use the older `defadvice` instead, see if that helps.

**Comment by thblt** [comment]
Just updated from the latest Melpa build, everything seems fine.  

On a related matter, should the advice really be added as soon as the package loading?  This made it quite hard to pin down the bug to highlight-indent-guides.  It seems logical (to me; I don't know much elisp) that most packages should generally have no effects when loading besides registering their autoloads, functions, customizations, etc.  Am I aiming at much more purity than elisp can provide?

**Comment by DarthFennec** [comment]
You are absolutely correct, the advice should not be enabled when the package is loaded. I was going to do this, but I guess it slipped my mind at the time. Just pushed, now the advice should be enabled and disabled with the mode.
