### ISSUE TITLE
Is this package orphaned?

### ISSUE THREAD

**Issue by agreselin** [DarthFennec/highlight-indent-guides#126]
This package seems unmaintained. GitHub says that the account https://github.com/DarthFennec hasn't had any activity since 2020. Should we users pick a fork to move to?

**Comment by bergey** [comment]
Thank you for volunteering! 😀  I'm interested in figuring out why hig doesn't highlight the html parts of `tsx-ts-mode` files.  After that I'm happy to help go through the backlog of PRs and issues.  Looks like there may be some unmerged fixes on others' forks, as well.

**Comment by agreselin** [comment]
@bergey No no no, there was a misunderstanding. I'm not volunteering to maintain this package, my Elisp-fu is not up to the task 😅

**Comment by bergey** [comment]
I'm sorry to hear it.  I think for a fairly mature package like this, what's needed is mostly someone to respond to bug reports and help the reporter debug.  If you don't want to take the lead, would you help me contact others with forks, see if any of them are willing?

**Comment by agreselin** [comment]
Hi @bergey, sorry for the late reply. I don't have enough free time these days to take care of this package, but I had looked among the forks for the one that incorporates the most changes, which is https://github.com/getong/highlight-indent-guides

A few issues in this repo are related to tree-sitter support, if you need that you may like https://github.com/jdtsmith/indent-bars

**Comment by jcs090218** [comment]
cc @DarthFennec 🤔 

I hope the author is still maintaining this package. 😅

**Comment by bestlem** [comment]
@DarthFennec has done nothing in Github since Dec 2020 so I would assume this is orphaned

**Comment by DarthFennec** [comment]
Hey everyone! Yeah, sorry I fell off the earth for a few years, life happened. I'm getting into a slightly more stable place again now, so I'd like to try to start working on things like this again. But I can't be certain I'll have the bandwidth to maintain it like I used to, I haven't even used emacs in years.

I'm still deciding what I'm gonna do with this project, but for the moment I'd like to look for someone to help handle things. Happy to consider volunteers if anyone is interested!

I also have a new GitHub account, which I should probably move this to. If you see this person it's me: https://github.com/meowntaineer

I'll make some time next week to catch up with things around here and get a more solid plan together. Cheers!

**Comment by jcs090218** [comment]
I volunteer myself as a maintainer/collaborator. :)

Regarding myself, I serve as the primary maintainer for `emacs-dashboard` and one of the maintainers for `lsp-mode`. I have developed over a hundred Emacs packages. Hope I am qualified to help maintain this package. :D

**Comment by agreselin** [comment]
Thanks for this Christmas present @jcs090218! What are the next steps, are you going to fork it and upload it to MELPA with another name?

**Comment by jcs090218** [comment]
The simplest solution is for Emily to add me as a collaborator so I have minimalist control to help maintain this package. 😉 Unless Emily has other plans, like move to an org or new account, etc. 🤔

**Comment by meowntaineer** [comment]
Alright, I added @jcs090218 to the project so y'all can finally get some work done. I'm gonna try to migrate everything to my new account soon, and we can figure the rest out from there. Thanks for hanging in there, cheers!

**Comment by jcs090218** [comment]
@DarthFennec @meowntaineer Thank you! :D Merry Christmas! 🎄 🎁 ☃️

**Comment by jcs090218** [comment]
Since I am maintaining this package, I am closing it now. :)
