### ISSUE TITLE
Using rainbow-delimiters for colors

### ISSUE THREAD

**Issue by Flinner** [DarthFennec/highlight-indent-guides#127]
What do you think of using `rainbow-delimiters` package for colors? It provides nice colors regardless of color scheme?

https://github.com/Fanael/rainbow-delimiters

If a clean function were to be written, would you want a PR?

Also this could be a stupid suggestion, I'm sorry in advance :<

**Comment by LoganBarnett** [comment]
@Flinner did you close this because you solved the issue in some way?  Seems like a reasonable request to me, especially if you were willing to submit a PR.  I found this ticket looking for the same feature.

**Comment by Flinner** [comment]
I thought it was a silly issue and not valid :sweat_smile:
