### ISSUE TITLE
dotted lines instead of color boxes? 

### ISSUE THREAD

**Issue by timmli** [DarthFennec/highlight-indent-guides#2]
Is it possible to show vertical dotted lines (as in Sublime Text) instead of using color boxes?

Thanks for the package!

**Comment by DarthFennec** [comment]
Sadly, not at the moment. There is a mode that can do something similar to this, [zk-phi/indent-guide](https://github.com/zk-phi/indent-guide), but in my experience that mode tends to be laggy and jittery, and it also doesn't play too well with other modes.

The main issue is that displaying text or images (such as a dotted line) in this way would generally require the use of overlays, which I would really like to avoid using in this mode. Overlays are great, but when there are a lot of them (as would generally be the case when you use them as indentation guides), they get difficult to manage, and things start to run really slow. Also, overlays seem to have a tendency to interfere with each other unexpectedly. This mode avoids both of those problems by drawing its guides with font-lock, but this limits the mode to only modifying text color and other text properties.

I've actually been looking into a method of doing this using the `display` text property, but I'm not sure whether this is viable yet. In any case, if I find a way to do this that I'm comfortable with, I'll certainly include it.

**Comment by DarthFennec** [comment]
So my latest commit allows you to choose between color boxes, vertical color lines, and vertical lines drawn with a character. That last one should be what you're looking for. I personally like the solid line character I set as default, but if you can find a dotted one you like better (or any other character for that matter), you can use that instead.

Please let me know if this helps.

**Comment by timmli** [comment]
Awesome! That's what I was looking for. So the latest commit solved the issue for me.

**Comment by DarthFennec** [comment]
Great! Glad to hear.
