### ISSUE TITLE
conflict with whitespace-mode

### ISSUE THREAD

**Issue by gongzhitaao** [DarthFennec/highlight-indent-guides#24]
This seems to conflict with `whitespace-mode`.

The following *WORKS*

```emacs-lisp
(add-hook 'prog-mode-hook #'highlight-indent-guides-mode)
(add-hook 'prog-mode-hook #'whitespace-mode)
```

But the following *DOES NOT WORK*

```emacs-lisp
(add-hook 'prog-mode-hook #'whitespace-mode)
(add-hook 'prog-mode-hook #'highlight-indent-guides-mode)
```
By *work (not work)* I mean the indent guide overlay is showing (not showing)

I think the problem is that both packages try to change the display of whitespace characters.

**Comment by DarthFennec** [comment]
Yes, I think this has to do with the order the modes are adding themselves to `font-lock-keywords`. Both modes add to the end of the list, and keywords earlier in the list take precedence, so whichever mode is hooked first in your config file is going to show up in place of the other. This is normal, and is going to happen with any two modes that set the same fontification properties on the same characters. After all, a character can't have two background colors at once. So this isn't a conflict as far as I can tell, unless there's something I'm misunderstanding?

**Comment by gongzhitaao** [comment]
Well, yes, I totally agree with you.  I think this issue could be closed.
