### ISSUE TITLE
error: Invalid face, highlight-indent-guides-odd-face using hex color

### ISSUE THREAD

**Issue by treymerkley** [DarthFennec/highlight-indent-guides#30]
Hey, this is great stuff, really light on the system, but when I try to use this with a hexadecimal color like so:

`
(add-hook 'prog-mode-hook 'highlight-indent-guides-mode)
(setq highlight-indent-guides-method 'column)
(setq highlight-indent-guides-auto-enabled nil)
(set-face-background 'highlight-indent-guides-odd-face "#93a1a1")
(set-face-background 'highlight-indent-guides-even-face "#93a1a1")
(set-face-foreground 'highlight-indent-guides-character-face "#93a1a1")
`

Emacs tells me it can't use those colors. However, when I open my init file and run

`
M-x load-file RET RET
`

It runs just fine, using the appropriate colors. How do I set it to load this initially?

**Comment by DarthFennec** [comment]
Unable to reproduce, hex colors work just fine for me. Are you sure this same config works with non-hex colors? Can you paste me the error it's giving you?

If it doesn't work on initial load, but then it works after you `load-file`, it sounds like you might be setting the faces before they exist. Make sure you `(require 'highlight-indent-guides)` before any other calls related to `highlight-indent-guides`.

**Comment by treymerkley** [comment]
Adding that line fixed the problem for me. Thanks!

**Comment by DarthFennec** [comment]
Glad to help!
