### ISSUE TITLE
Is it possible to disable in ivy minibuffers?

### ISSUE THREAD

**Issue by seagle0128** [DarthFennec/highlight-indent-guides#38]
I noticed `highlight-indent-guides` breaks or slows down `ivy` minibuffers some times, although it's much better than before. e.g. in `counsel-yank-pop`, I got errors some times.

So my question is that is it possible to disable it in Ivy minibuffers? Thanks!

**Comment by jgkamat** [comment]
@seagle0128, how are you enabling this mode? the example in the readme uses:

```
(add-hook 'prog-mode-hook 'highlight-indent-guides-mode)
```

which should only activate it in prog mode buffers (which the minibuffer shouldn't be).

I personally added it for prog, nxml, and yaml modes.

**Comment by jgkamat** [comment]
this mode isn't enabled in the minibuffer, it's just displaying all the properties (?) from the yanked region.

If you yank when guides are enabled, then turn them off and yank again, you can see that it's not enabled for every line:

![2018-05-26-201715_669x161_scrot](https://user-images.githubusercontent.com/4349709/40582168-98111df0-615c-11e8-9ddf-0e2f49178980.png)

Furthermore, if you [enable recursive minibfufers](http://www.gnu.org/software/emacs/manual/html_node/elisp/Recursive-Mini.html), you will find that `highlight-indent-guides-mode` is nil in the minibuffer.

You might want to see if there's a way to remove the property in ivy instead.

**Comment by seagle0128** [comment]
OK. Maybe it's the correct question. I got another screenshot.

![image](https://user-images.githubusercontent.com/140797/40583055-c7063d28-61b8-11e8-8afb-44ad02712a7d.png)

**Comment by seagle0128** [comment]
I am using `20180518.1624`. Is it the latest version?

**Comment by seagle0128** [comment]
Thanks for the quick fixing! Waiting for the next version.

**Comment by seagle0128** [comment]
Seems the fix works for me. Closing it. Thanks again!

**Comment by DarthFennec** [comment]
Awesome! Glad that did the trick.
