### ISSUE TITLE
'character style looking dashed

### ISSUE THREAD

**Issue by vemv** [DarthFennec/highlight-indent-guides#43]
Hi!

Excellent-looking package, kudos.

I'm seeing this, don't know the cause:

![image](https://user-images.githubusercontent.com/1162994/43694174-66d0f2fc-9932-11e8-8035-d38e3fa3e78d.png)

I don't have `line-spacing` customized.

Cheers - Victor

**Comment by vemv** [comment]
It looks somewhat better with https://www.compart.com/en/unicode/U+FF5C

I'm using the Monaco font, one of the post popular on Mac. Tried Andale Mono and Courier as well, no luck

**Comment by vemv** [comment]
Thanks for the reply!

I tried out that one font, to no avail. Tried different emacsen (emacs-mac, emacsformacosx), ensured `line-spacing` wasn't customized.

Perhaps there's something simple going on that doesn't require as much work as #35 ?

**Comment by DarthFennec** [comment]
I'm not running macos, so I don't know if there's some difference in general with how emacs renders on that system. I wouldn't imagine that it's something you can easily fix with a configuration change, though. From your screenshot it just looks like your font's glyph is too small, but if you get the same thing with Source Code Pro then I just don't know.

**Comment by vemv** [comment]
Alright, issue seems reasonable to close then. Fingers crossed for having #35 at some point!

**Comment by DarthFennec** [comment]
#35 is done, let me know if you have any problems with it.
