### ISSUE TITLE
Please add a mode line lighter

### ISSUE THREAD

**Issue by re-mx** [DarthFennec/highlight-indent-guides#47]
Hello, and sorry for my poor English.

Please consider adding a mode line display. This makes it easy to see if `highlight-indent-guides` is turned on or not.
Those who don't need it can hide it with plugins like `diminish`.

Thank you.

**Comment by DarthFennec** [comment]
You're right. I don't use lighters so it didn't occur to me, but I understand it's a useful part of other peoples' workflows. Added.
