### ISSUE TITLE
 [low priority] latest version `highlight-indent-guides-20190108.3` not showing guides under `web-mode-20190506.607`

### ISSUE THREAD

**Issue by dennismayr** [DarthFennec/highlight-indent-guides#58]
Latest version `highlight-indent-guides-20190108.3` is not showing [indentation guides](https://github.com/fxbois/web-mode/issues/1062) under `web-mode-20190506.607`.
Guides, however, are shown under other modes.

Edit: issue happens beyond 90 lines of HTML code; first 90 lines do show indentation guides.

Emacs 26.2
Spacemacs 0.300.0
Ubuntu 18.04

**Comment by jcs090218** [comment]
Does the newest version resolved your issue?

**Comment by dennismayr** [comment]
Hi @jcs090218!

Unfortunately, it hasn't.

I had found an error message related to an apparently conflictive line: it's interpreted as an open _HTML_ `<a>` tag when it's in fact closed:

![Imgur](https://imgur.com/YSteua1.png) 

However, I've commented-out the line, and the problem persists:

![Imgur](https://imgur.com/cHP0RyS.png)

I'll check with the `web-mode` maintainer; can we keep this issue open for a few extra days?

**Comment by jcs090218** [comment]
@dennismayr No worries! I just really like this plugin and willing to contribute to this project. I wasn't really known your question until now, and thought the problem was already resolved in the newest version. Thanks for explaining! :D

**Comment by DarthFennec** [comment]
With your `<a>` line, you didn't close your class string. It seems like that would cause emacs to think the entire rest of the file was a string, which would prevent it from drawing guides. I'm not sure if commenting the line out would change this. If this is the only file you're getting this behavior in, I expect that's the cause.

**Comment by dennismayr** [comment]
@DarthFennec You're absolutely right!

I should take more pauses during work, this totally slid before my very own eyes.

Closing the issue.
