### ISSUE TITLE
Guide color

### ISSUE THREAD

**Issue by cbarnabas** [DarthFennec/highlight-indent-guides#63]
Has anyone had success recently with manually setting the guide color?
No matter what colors I use I get black guides. 
![2019-10-04-122753_1920x1080_scrot](https://user-images.githubusercontent.com/44208860/66234433-91664580-e6a2-11e9-937c-e2c7895b9f07.png)

**Comment by DarthFennec** [comment]
It looks like you're using the `character` method. In that case, you have to set:

```emacs-lisp
(require 'highlight-indent-guides)
(setq highlight-indent-guides-auto-enabled nil)
(set-face-foreground 'highlight-indent-guides-character-face "color here")
```

Note how I use `set-face-foreground` instead of `set-face-background`, since you're coloring the actual characters instead of the background color. Let me know if that works for you. Thanks!

**Comment by cbarnabas** [comment]
Ah, thank you! Works like a charm.
