### ISSUE TITLE
Doesn't work well with adaptive-wrap package

### ISSUE THREAD

**Issue by CSRaghunandan** [DarthFennec/highlight-indent-guides#72]
If I have the `adaptive-wrap-prefix-mode` enabled, all the indent guides(which are line wrapped by `adaptive-wrap-prefix-mode`) are white instead of actual face which is calculated from the default theme, whereas all the other indent guides are of the correct color.

**Comment by DarthFennec** [comment]
Same issue as #29?

**Comment by CSRaghunandan** [comment]
> Same issue as #29?

Oh yeah, looks like the same issue. I didn't realize since the title was not informative. I'm closing this in favor of the older issue.
