### ISSUE TITLE
 Stuck under js(x) files

### ISSUE THREAD

**Issue by glepnir** [DarthFennec/highlight-indent-guides#74]
Hi  , open a js or jsx files ,it has 200+lines. then Keep press `j` to move next line .very stuck when open highlight-indent-guides-mode.
![test](https://user-images.githubusercontent.com/41671631/76414136-b4bfba00-63d1-11ea-81a2-438f48f92a62.gif)

**Comment by DarthFennec** [comment]
I'm not sure I understand, how does it get stuck? The gif looks like it's working fine to me.

**Comment by taigacute** [comment]
next line move is not smooth..

**Comment by DarthFennec** [comment]
Like, those jumps of a few lines at a time at the beginning? What exactly are you doing to make this happen, are you tapping the key or holding it or something else? How accurate is the gif, it is dropping frames or is that exactly what you're seeing? Maybe if you could post a gif of you doing the same thing with the mode disabled, I can see the difference more clearly. That might help me better understand what's going on.
