### ISSUE TITLE
Enable remote tests

### ISSUE THREAD

**Issue by andreas-roehler** [DarthFennec/highlight-indent-guides#92]
Running remote tests enhances reliability. Notably, some files might be not be committed but exist on the local machine. So tests succeed locally but should fail in this case.

**Comment by DarthFennec** [comment]
I set up this: https://travis-ci.org/github/DarthFennec/highlight-indent-guides
I had trouble viewing the one you linked, something about it not being active. I guess this will show results the next time there's a commit.
