### ISSUE TITLE
Guides barely visible in dark theme

### ISSUE THREAD

**Issue by mcp292** [DarthFennec/highlight-indent-guides#99]
## Default

![2020-09-22_13-25](https://user-images.githubusercontent.com/49123398/93934024-6328ae00-fcd7-11ea-816f-f4912d6ddb3e.png)

## Manoj Dark

![2020-09-22_13-25_1](https://user-images.githubusercontent.com/49123398/93934001-5dcb6380-fcd7-11ea-8a3d-468c5e5c96d3.png)

**Comment by DarthFennec** [comment]
Yeah, I see what you mean. Try customizing your `highlight-indent-guides-auto-character-face-perc`? That will change the contrast so the color shows up better.

**Comment by mcp292** [comment]
That worked! 

Is there any to specify one value for my dark theme and a lower value for my light?

**Comment by DarthFennec** [comment]
Not really, no. I'd suggest just trying to find a value that works alright for both. If that really doesn't work for you, as a workaround you can turn off dynamic colors and set your colors manually, maybe add an advice for `load-theme` that sets them automatically when you change theme. Or something like that.

**Comment by mcp292** [comment]
That's okay. I was able to find a middle ground I was happy with. Appreciate the workaround!
